//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDS
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donor
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        public string Gender { get; set; }
        public int Blood_Group { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public int Area { get; set; }
        public Nullable<bool> Active { get; set; }
        public string CreateDate { get; set; }
        public string Second_Name { get; set; }
    }
}
